test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.68367353.name = "Upgrade from 3.6.1~ynh2"
    