test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.511bcaf0.name = "Upgrade from 3.3.2"
    