#!/usr/bin/env bash
set -e

source /usr/share/yunohost/helpers

app="${0//.\/50-}"
user=$1

final_path="$(ynh_app_setting_get --app=$app --key=final_path)"
enable_extensions="$(ynh_app_setting_get --app=$app --key=enable_extensions)"

ynh_use_nodejs

if [ $enable_extensions -eq 1 ]; then
	export JUPYTERLAB_DIR="$(getent passwd $user | cut -d: -f6)/.local/share/$app/lab"
	node_path="$nodejs_path:$(sudo -u $user sh -c 'echo $PATH')"
	sudo -u $user env "PATH=$node_path:$PATH" "$final_path/.venv/bin/jupyter" lab build --app-dir="$JUPYTERLAB_DIR"
fi
