#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
#REMOVEME? ynh_script_progression --message="Loading installation settings..." --weight=1

#REMOVEME? app=$YNH_APP_INSTANCE_NAME

#REMOVEME? domain="$(ynh_app_setting_get --app=$app --key=domain)"
#REMOVEME? path="$(ynh_app_setting_get --app=$app --key=path)"
#REMOVEME? admin="$(ynh_app_setting_get --app=$app --key=admin)"
#REMOVEME? #REMOVEME? install_dir="$(ynh_app_setting_get --app=$app --key=install_dir)"
#REMOVEME? port="$(ynh_app_setting_get --app=$app --key=port)"
#REMOVEME? port_hub="$(ynh_app_setting_get --app=$app --key=port_hub)"
#REMOVEME? port_http_proxy="$(ynh_app_setting_get --app=$app --key=port_http_proxy)"
#REMOVEME? enable_terminal="$(ynh_app_setting_get --app=$app --key=enable_terminal)"
#REMOVEME? enable_extensions="$(ynh_app_setting_get --app=$app --key=enable_extensions)"

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

# Remove a service from the admin panel, added by `yunohost service add`
if ynh_exec_warn_less yunohost service status $app >/dev/null
then
	ynh_script_progression --message="Removing $app service..." --weight=2
	yunohost service remove $app
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression --message="Stopping and removing the systemd service..." --weight=2

# Remove the dedicated systemd config
ynh_remove_systemd_config

#=================================================
# REMOVE DEPENDENCIES
#=================================================
#REMOVEME? ynh_script_progression --message="Removing dependencies..." --weight=4

# Remove metapackage and its dependencies
#REMOVEME? ynh_remove_app_dependencies

ynh_remove_nodejs

#=================================================
# REMOVE APP MAIN DIR
#=================================================
#REMOVEME? ynh_script_progression --message="Removing app main directory..." --weight=1

# Remove the app directory securely
#REMOVEME? ynh_secure_remove --file="$install_dir"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing NGINX web server configuration..." --weight=1

# Remove the dedicated NGINX config
ynh_remove_nginx_config

#=================================================
# REMOVE SUDOERS CONFIGURATION
#=================================================
ynh_script_progression --message="Removing sudoers configuration..." --weight=1

# Remove the dedicated NGINX config
ynh_secure_remove "/etc/sudoers.d/$app-sudoers"

#=================================================
# CLOSE A PORT
#=================================================

if yunohost firewall list | grep -q "\- $port$"
then
	ynh_script_progression --message="Closing port $port..."
	ynh_exec_warn_less yunohost firewall disallow TCP $port
fi

if yunohost firewall list | grep -q "\- $port_hub$"
then
	ynh_script_progression --message="Closing port $port_hub..."
	ynh_exec_warn_less yunohost firewall disallow TCP $port_hub
fi

if yunohost firewall list | grep -q "\- $port_http_proxy$"
then
	ynh_script_progression --message="Closing port $port_http_proxy..."
	ynh_exec_warn_less yunohost firewall disallow TCP $port_http_proxy
fi

#=================================================
# REMOVE DEDICATED USER
#=================================================
#REMOVEME? ynh_script_progression --message="Removing the dedicated system user..." --weight=1

# Delete a system user
#REMOVEME? ynh_system_user_delete --username=$app

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
